// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestThanhToan
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_ThanhToan
        /// </summary>
        public void RecordedMethod_ThanhToan()
        {
            #region Variable Declarations
            WinWindow uIItem1Window = this.UIBanWindow.UIPanel3Window.UIItem1Window;
            WinWindow uIThanhToánWindow = this.UIBanWindow.UIPanel2Window.UIThanhToánWindow;
            #endregion

            // Click '1' window
            Mouse.Click(uIItem1Window, new Point(90, 274));

            // Click 'Thanh Toán' window
            Mouse.Click(uIThanhToánWindow, new Point(626, 201));
        }
        
        /// <summary>
        /// AssertMethod_ThanhToan - Use 'AssertMethod_ThanhToanExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_ThanhToan()
        {
            #region Variable Declarations
            WinWindow uITxtTongTienThanhToanWindow = this.UIBanWindow.UIPanel2Window.UITxtTongTienThanhToanWindow;
            #endregion

            // Verify that the 'ControlName' property of 'txtTongTienThanhToan' window equals '60000'
            Assert.AreEqual(this.AssertMethod_ThanhToanExpectedValues.UITxtTongTienThanhToanWindowControlName, uITxtTongTienThanhToanWindow.ControlName, "Lỗi");
        }
        
        /// <summary>
        /// RecordedMethod_ThanhToan1 - Use 'RecordedMethod_ThanhToan1Params' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_ThanhToan1()
        {
            #region Variable Declarations
            WinWindow uIItem3Window = this.UIBanWindow.UIPanel3Window.UIItem3Window;
            WinWindow uITxtTienKhachDuaWindow = this.UIBanWindow.UIPanel2Window.UITxtTienKhachDuaWindow;
            WinEdit uITxtTienKhachDuaEdit = this.UIBanWindow.UITxtTienKhachDuaWindow.UITxtTienKhachDuaEdit;
            WinWindow uIThanhToánWindow = this.UIBanWindow.UIPanel2Window.UIThanhToánWindow;
            #endregion

            uITxtTienKhachDuaEdit.SetFocus();
            // Click '3' window
            Mouse.Hover(new Point(700,700));
            Mouse.Click();

            // Click 'txtTienKhachDua' window
            Mouse.Hover(new Point(1300, 550));
            Mouse.Click();
           

            // Type '30000' in 'txtTienKhachDua' text box
            Keyboard.SendKeys("30000");
            //uITxtTienKhachDuaEdit.Text = this.RecordedMethod_ThanhToan1Params.UITxtTienKhachDuaEditText;

            // Click 'Thanh Toán' window
            Mouse.Hover(new Point(1600, 550));
            Mouse.Click();
        }
        
        /// <summary>
        /// AssertMethod_ThanhToan1 - Use 'AssertMethod_ThanhToan1ExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_ThanhToan1()
        {
            #region Variable Declarations
            WinEdit uITxtTrangThaiWindow = this.UIBanWindow.UITrangThaiWindow.UITxtTrangThaiEdit;
            #endregion

            // Verify that the 'ControlName' property of 'txtTrangThai' window equals 'Thanh toán thành công'
            Assert.AreEqual(this.AssertMethod_ThanhToan1ExpectedValues.UITxtTrangThaiWindowControlName, uITxtTrangThaiWindow.Text, "Thanh toán lỗi");
        }
        
        #region Properties
        public virtual AssertMethod_ThanhToanExpectedValues AssertMethod_ThanhToanExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_ThanhToanExpectedValues == null))
                {
                    this.mAssertMethod_ThanhToanExpectedValues = new AssertMethod_ThanhToanExpectedValues();
                }
                return this.mAssertMethod_ThanhToanExpectedValues;
            }
        }
        
        public virtual RecordedMethod_ThanhToan1Params RecordedMethod_ThanhToan1Params
        {
            get
            {
                if ((this.mRecordedMethod_ThanhToan1Params == null))
                {
                    this.mRecordedMethod_ThanhToan1Params = new RecordedMethod_ThanhToan1Params();
                }
                return this.mRecordedMethod_ThanhToan1Params;
            }
        }
        
        public virtual AssertMethod_ThanhToan1ExpectedValues AssertMethod_ThanhToan1ExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_ThanhToan1ExpectedValues == null))
                {
                    this.mAssertMethod_ThanhToan1ExpectedValues = new AssertMethod_ThanhToan1ExpectedValues();
                }
                return this.mAssertMethod_ThanhToan1ExpectedValues;
            }
        }
        
        public UIBanWindow UIBanWindow
        {
            get
            {
                if ((this.mUIBanWindow == null))
                {
                    this.mUIBanWindow = new UIBanWindow();
                }
                return this.mUIBanWindow;
            }
        }
        #endregion
        
        #region Fields
        private AssertMethod_ThanhToanExpectedValues mAssertMethod_ThanhToanExpectedValues;
        
        private RecordedMethod_ThanhToan1Params mRecordedMethod_ThanhToan1Params;
        
        private AssertMethod_ThanhToan1ExpectedValues mAssertMethod_ThanhToan1ExpectedValues;
        
        private UIBanWindow mUIBanWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_ThanhToan'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertMethod_ThanhToanExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlName' property of 'txtTongTienThanhToan' window equals '60000'
        /// </summary>
        public string UITxtTongTienThanhToanWindowControlName = "60000";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_ThanhToan1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethod_ThanhToan1Params
    {
        
        #region Fields
        /// <summary>
        /// Type '30000' in 'txtTienKhachDua' text box
        /// </summary>
        public string UITxtTienKhachDuaEditText = "30000";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_ThanhToan1'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertMethod_ThanhToan1ExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlName' property of 'txtTrangThai' window equals 'Thanh toán thành công'
        /// </summary>
        public string UITxtTrangThaiWindowControlName = "Thanh toán thành công";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIBanWindow : WinWindow
    {
        
        public UIBanWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Ban";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Ban");
            #endregion
        }
        
        #region Properties
        public UIPanel3Window UIPanel3Window
        {
            get
            {
                if ((this.mUIPanel3Window == null))
                {
                    this.mUIPanel3Window = new UIPanel3Window(this);
                }
                return this.mUIPanel3Window;
            }
        }
        
        public UIPanel2Window UIPanel2Window
        {
            get
            {
                if ((this.mUIPanel2Window == null))
                {
                    this.mUIPanel2Window = new UIPanel2Window(this);
                }
                return this.mUIPanel2Window;
            }
        }


        //trạng thái

        public UITxtTrangThaiWindow UITrangThaiWindow
        {
            get
            {
                if ((this.mUITxtTrangThaiWindow == null))
                {
                    this.mUITxtTrangThaiWindow = new UITxtTrangThaiWindow(this);
                }
                return this.mUITxtTrangThaiWindow;
            }
        }
         #endregion
        
        #region Fields
        
        private UITxtTrangThaiWindow mUITxtTrangThaiWindow;
        #endregion
        
        public UITxtTienKhachDuaWindow UITxtTienKhachDuaWindow
        {
            get
            {
                if ((this.mUITxtTienKhachDuaWindow == null))
                {
                    this.mUITxtTienKhachDuaWindow = new UITxtTienKhachDuaWindow(this);
                }
                return this.mUITxtTienKhachDuaWindow;
            }
        }
        
        
        #region Fields
        private UIPanel3Window mUIPanel3Window;
        
        private UIPanel2Window mUIPanel2Window;
        
        private UITxtTienKhachDuaWindow mUITxtTienKhachDuaWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPanel3Window : WinWindow
    {
        
        public UIPanel3Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "panel3";
            this.WindowTitles.Add("Ban");
            #endregion
        }
        
        #region Properties
        public WinWindow UIItem1Window
        {
            get
            {
                if ((this.mUIItem1Window == null))
                {
                    this.mUIItem1Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItem1Window.SearchProperties[WinWindow.PropertyNames.Name] = "1";
                    this.mUIItem1Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIItem1Window.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUIItem1Window;
            }
        }
        
        public WinWindow UIItem3Window
        {
            get
            {
                if ((this.mUIItem3Window == null))
                {
                    this.mUIItem3Window = new WinWindow(this);
                    #region Search Criteria
                    this.mUIItem3Window.SearchProperties[WinWindow.PropertyNames.Name] = "3";
                    this.mUIItem3Window.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIItem3Window.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUIItem3Window;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIItem1Window;
        
        private WinWindow mUIItem3Window;
        #endregion
    }


    //trạng thái UITxtTrangThaiWindow
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtTrangThaiWindow : WinWindow
    {

        public UITxtTrangThaiWindow(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTrangThai";
            this.WindowTitles.Add("Ban");
            #endregion
        }

        #region Properties
        public WinEdit UITxtTrangThaiEdit
        {
            get
            {
                if ((this.mUITxtTrangThaiEdit == null))
                {
                    this.mUITxtTrangThaiEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTrangThaiEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Trạng Thái";
                    this.mUITxtTrangThaiEdit.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUITxtTrangThaiEdit;
            }
        }
        #endregion

        #region Fields
        private WinEdit mUITxtTrangThaiEdit;
        #endregion
    }


    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPanel2Window : WinWindow
    {
        
        public UIPanel2Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "panel2";
            this.WindowTitles.Add("Ban");
            #endregion
        }
        
        #region Properties
        public WinWindow UIThanhToánWindow
        {
            get
            {
                if ((this.mUIThanhToánWindow == null))
                {
                    this.mUIThanhToánWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUIThanhToánWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Thanh Toán";
                    this.mUIThanhToánWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUIThanhToánWindow.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUIThanhToánWindow;
            }
        }
        
        public WinWindow UITxtTongTienThanhToanWindow
        {
            get
            {
                if ((this.mUITxtTongTienThanhToanWindow == null))
                {
                    this.mUITxtTongTienThanhToanWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtTongTienThanhToanWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Tổng tiền";
                    this.mUITxtTongTienThanhToanWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtTongTienThanhToanWindow.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUITxtTongTienThanhToanWindow;
            }
        }
        
        public WinWindow UITxtTienKhachDuaWindow
        {
            get
            {
                if ((this.mUITxtTienKhachDuaWindow == null))
                {
                    this.mUITxtTienKhachDuaWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtTienKhachDuaWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Tiền khách đưa";
                    this.mUITxtTienKhachDuaWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtTienKhachDuaWindow.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUITxtTienKhachDuaWindow;
            }
        }
        
        public WinWindow UITxtTrangThaiWindow
        {
            get
            {
                if ((this.mUITxtTrangThaiWindow == null))
                {
                    this.mUITxtTrangThaiWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtTrangThaiWindow.SearchProperties[WinWindow.PropertyNames.AccessibleName] = "Trạng Thái";
                    this.mUITxtTrangThaiWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtTrangThaiWindow.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUITxtTrangThaiWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUIThanhToánWindow;
        
        private WinWindow mUITxtTongTienThanhToanWindow;
        
        private WinWindow mUITxtTienKhachDuaWindow;
        
        private WinWindow mUITxtTrangThaiWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtTienKhachDuaWindow : WinWindow
    {
        
        public UITxtTienKhachDuaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTienKhachDua";
            this.WindowTitles.Add("Ban");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtTienKhachDuaEdit
        {
            get
            {
                if ((this.mUITxtTienKhachDuaEdit == null))
                {
                    this.mUITxtTienKhachDuaEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTienKhachDuaEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Tiền khách đưa";
                    this.mUITxtTienKhachDuaEdit.WindowTitles.Add("Ban");
                    #endregion
                }
                return this.mUITxtTienKhachDuaEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtTienKhachDuaEdit;
        #endregion
    }
}
