// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace CodedUITestNhaCungCap
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public partial class UIMap
    {
        
        /// <summary>
        /// RecordedMethod_SuaNCC - Use 'RecordedMethod_SuaNCCParams' to pass parameters into this method.
        /// </summary>
        public void RecordedMethod_SuaNCC()
        {
            #region Variable Declarations
            WinWindow uISửaWindow = this.UINhàCungCấpWindow.UIDANHMỤCNHÀCUNGCẤPClient.UISửaWindow;
            WinClient uIPanel1Client = this.UINhàCungCấpWindow.UIPanel1Window.UIPanel1Client;
            WinButton uISửaButton = this.UINhàCungCấpWindow.UISửaWindow.UISửaButton;
            WinEdit uITxttenEdit = this.UINhàCungCấpWindow.UITxttenWindow.UITxttenEdit;
            WinEdit uITxtdcEdit = this.UINhàCungCấpWindow.UITxtdcWindow.UITxtdcEdit;
            WinEdit uITxtdtEdit = this.UINhàCungCấpWindow.UITxtdtWindow.UITxtdtEdit;
            WinButton uILưuButton = this.UINhàCungCấpWindow.UILưuWindow.UILưuButton;
            WinWindow uITxtTrangThaiWindow = this.UINhàCungCấpWindow.UIDANHMỤCNHÀCUNGCẤPClient.UITxtTrangThaiWindow;
            #endregion

            // Click 'Sửa' window
            //Mouse.Click(uISửaWindow, new Point(342, 109));

            // Click 'panel1' client
            //Mouse.Click(uIPanel1Client, new Point(471, 47));

           

            // Type '{Enter}' in 'Sửa' button
            Keyboard.SendKeys(uISửaButton, this.RecordedMethod_SuaNCCParams.UISửaButtonSendKeys, ModifierKeys.None);
            uITxttenEdit.SelectionStart = 0;
            Keyboard.SendKeys("");
            // Type 'E' in 'txtten' text box
            //uITxttenEdit.Text = this.RecordedMethod_SuaNCCParams.UITxttenEditText;

            // Type '{CapsLock}{Tab}' in 'txtten' text box
            Keyboard.SendKeys(uITxttenEdit, this.RecordedMethod_SuaNCCParams.UITxttenEditSendKeys, ModifierKeys.None);
            uITxtdcEdit.SelectionStart = 0;
            Keyboard.SendKeys("TPHCM");
            // Type 'TPHCM' in 'txtdc' text box
            //uITxtdcEdit.Text = this.RecordedMethod_SuaNCCParams.UITxtdcEditText;

            // Type '{Tab}' in 'txtdc' text box
            Keyboard.SendKeys(uITxtdcEdit, this.RecordedMethod_SuaNCCParams.UITxtdcEditSendKeys, ModifierKeys.None);
            uITxtdtEdit.SelectionStart = 0;
            Keyboard.SendKeys("012345678");
            // Type '0123456' in 'txtdt' text box
            //uITxtdtEdit.Text = this.RecordedMethod_SuaNCCParams.UITxtdtEditText;

            // Type '{CapsLock}{Tab}' in 'txtdt' text box
            Keyboard.SendKeys(uITxtdtEdit, this.RecordedMethod_SuaNCCParams.UITxtdtEditSendKeys, ModifierKeys.None);

            // Type '{Enter}' in 'Lưu' button
            Keyboard.SendKeys(uILưuButton, this.RecordedMethod_SuaNCCParams.UILưuButtonSendKeys, ModifierKeys.None);

            // Click 'txtTrangThai' window
            //Mouse.Click(uITxtTrangThaiWindow, new Point(530, 113));
        }
        
        /// <summary>
        /// AssertMethod_NCC - Use 'AssertMethod_NCCExpectedValues' to pass parameters into this method.
        /// </summary>
        public void AssertMethod_NCC()
        {
            #region Variable Declarations
            WinEdit uITxtTrangThaiWindow = this.UINhàCungCấpWindow.UITrangThaiWindow.UITxtTrangThaiEdit;
            #endregion

            // Verify that the 'ControlName' property of 'txtTrangThai' window equals 'Sửa thành công'
            Assert.AreEqual(this.AssertMethod_NCCExpectedValues.UITxtTrangThaiWindowControlName, uITxtTrangThaiWindow.Text, "Sửa Lỗi");
        }
        
        #region Properties
        public virtual RecordedMethod_SuaNCCParams RecordedMethod_SuaNCCParams
        {
            get
            {
                if ((this.mRecordedMethod_SuaNCCParams == null))
                {
                    this.mRecordedMethod_SuaNCCParams = new RecordedMethod_SuaNCCParams();
                }
                return this.mRecordedMethod_SuaNCCParams;
            }
        }
        
        public virtual AssertMethod_NCCExpectedValues AssertMethod_NCCExpectedValues
        {
            get
            {
                if ((this.mAssertMethod_NCCExpectedValues == null))
                {
                    this.mAssertMethod_NCCExpectedValues = new AssertMethod_NCCExpectedValues();
                }
                return this.mAssertMethod_NCCExpectedValues;
            }
        }
        
        public UINhàCungCấpWindow UINhàCungCấpWindow
        {
            get
            {
                if ((this.mUINhàCungCấpWindow == null))
                {
                    this.mUINhàCungCấpWindow = new UINhàCungCấpWindow();
                }
                return this.mUINhàCungCấpWindow;
            }
        }
        #endregion
        
        #region Fields
        private RecordedMethod_SuaNCCParams mRecordedMethod_SuaNCCParams;
        
        private AssertMethod_NCCExpectedValues mAssertMethod_NCCExpectedValues;
        
        private UINhàCungCấpWindow mUINhàCungCấpWindow;
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'RecordedMethod_SuaNCC'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class RecordedMethod_SuaNCCParams
    {
        
        #region Fields
        /// <summary>
        /// Type '{Enter}' in 'Sửa' button
        /// </summary>
        public string UISửaButtonSendKeys = "{Enter}";
        
        /// <summary>
        /// Type 'E' in 'txtten' text box
        /// </summary>
        public string UITxttenEditText = "E";
        
        /// <summary>
        /// Type '{CapsLock}{Tab}' in 'txtten' text box
        /// </summary>
        public string UITxttenEditSendKeys = "{CapsLock}{Tab}";
        
        /// <summary>
        /// Type 'TPHCM' in 'txtdc' text box
        /// </summary>
        public string UITxtdcEditText = "TPHCM";
        
        /// <summary>
        /// Type '{Tab}' in 'txtdc' text box
        /// </summary>
        public string UITxtdcEditSendKeys = "{Tab}";
        
        /// <summary>
        /// Type '0123456' in 'txtdt' text box
        /// </summary>
        public string UITxtdtEditText = "0123456";
        
        /// <summary>
        /// Type '{CapsLock}{Tab}' in 'txtdt' text box
        /// </summary>
        public string UITxtdtEditSendKeys = "{CapsLock}{Tab}";
        
        /// <summary>
        /// Type '{Enter}' in 'Lưu' button
        /// </summary>
        public string UILưuButtonSendKeys = "{Enter}";
        #endregion
    }
    
    /// <summary>
    /// Parameters to be passed into 'AssertMethod_NCC'
    /// </summary>
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class AssertMethod_NCCExpectedValues
    {
        
        #region Fields
        /// <summary>
        /// Verify that the 'ControlName' property of 'txtTrangThai' window equals 'Sửa thành công'
        /// </summary>
        public string UITxtTrangThaiWindowControlName = "Sửa thành công";
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UINhàCungCấpWindow : WinWindow
    {
        
        public UINhàCungCấpWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Nhà Cung Cấp";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public UIDANHMỤCNHÀCUNGCẤPClient UIDANHMỤCNHÀCUNGCẤPClient
        {
            get
            {
                if ((this.mUIDANHMỤCNHÀCUNGCẤPClient == null))
                {
                    this.mUIDANHMỤCNHÀCUNGCẤPClient = new UIDANHMỤCNHÀCUNGCẤPClient(this);
                }
                return this.mUIDANHMỤCNHÀCUNGCẤPClient;
            }
        }
        
        public UIPanel1Window UIPanel1Window
        {
            get
            {
                if ((this.mUIPanel1Window == null))
                {
                    this.mUIPanel1Window = new UIPanel1Window(this);
                }
                return this.mUIPanel1Window;
            }
        }
        
        public UISửaWindow UISửaWindow
        {
            get
            {
                if ((this.mUISửaWindow == null))
                {
                    this.mUISửaWindow = new UISửaWindow(this);
                }
                return this.mUISửaWindow;
            }
        }
        
        public UITxttenWindow UITxttenWindow
        {
            get
            {
                if ((this.mUITxttenWindow == null))
                {
                    this.mUITxttenWindow = new UITxttenWindow(this);
                }
                return this.mUITxttenWindow;
            }
        }
        
        public UITxtdcWindow UITxtdcWindow
        {
            get
            {
                if ((this.mUITxtdcWindow == null))
                {
                    this.mUITxtdcWindow = new UITxtdcWindow(this);
                }
                return this.mUITxtdcWindow;
            }
        }
        
        public UITxtdtWindow UITxtdtWindow
        {
            get
            {
                if ((this.mUITxtdtWindow == null))
                {
                    this.mUITxtdtWindow = new UITxtdtWindow(this);
                }
                return this.mUITxtdtWindow;
            }
        }

        public UITxtTrangThaiWindow UITrangThaiWindow
        {
            get
            {
                if ((this.mUITxtTrangThaiWindow == null))
                {
                    this.mUITxtTrangThaiWindow = new UITxtTrangThaiWindow(this);
                }
                return this.mUITxtTrangThaiWindow;
            }
        }
        
        public UILưuWindow UILưuWindow
        {
            get
            {
                if ((this.mUILưuWindow == null))
                {
                    this.mUILưuWindow = new UILưuWindow(this);
                }
                return this.mUILưuWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIDANHMỤCNHÀCUNGCẤPClient mUIDANHMỤCNHÀCUNGCẤPClient;
        
        private UIPanel1Window mUIPanel1Window;
        
        private UISửaWindow mUISửaWindow;
        
        private UITxttenWindow mUITxttenWindow;
        
        private UITxtdcWindow mUITxtdcWindow;
        
        private UITxtdtWindow mUITxtdtWindow;

        private UITxtTrangThaiWindow mUITxtTrangThaiWindow;
        
        private UILưuWindow mUILưuWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIDANHMỤCNHÀCUNGCẤPClient : WinClient
    {
        
        public UIDANHMỤCNHÀCUNGCẤPClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.Name] = "DANH MỤC NHÀ CUNG CẤP";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public WinWindow UISửaWindow
        {
            get
            {
                if ((this.mUISửaWindow == null))
                {
                    this.mUISửaWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUISửaWindow.SearchProperties[WinWindow.PropertyNames.Name] = "Sửa";
                    this.mUISửaWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.BUTTON", PropertyExpressionOperator.Contains));
                    this.mUISửaWindow.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUISửaWindow;
            }
        }
        
        public WinWindow UITxtTrangThaiWindow
        {
            get
            {
                if ((this.mUITxtTrangThaiWindow == null))
                {
                    this.mUITxtTrangThaiWindow = new WinWindow(this);
                    #region Search Criteria
                    this.mUITxtTrangThaiWindow.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.EDIT", PropertyExpressionOperator.Contains));
                    this.mUITxtTrangThaiWindow.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUITxtTrangThaiWindow;
            }
        }
        #endregion
        
        #region Fields
        private WinWindow mUISửaWindow;
        
        private WinWindow mUITxtTrangThaiWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UIPanel1Window : WinWindow
    {
        
        public UIPanel1Window(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "panel1";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public WinClient UIPanel1Client
        {
            get
            {
                if ((this.mUIPanel1Client == null))
                {
                    this.mUIPanel1Client = new WinClient(this);
                    #region Search Criteria
                    this.mUIPanel1Client.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUIPanel1Client;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mUIPanel1Client;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UISửaWindow : WinWindow
    {
        
        public UISửaWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btsua";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public WinButton UISửaButton
        {
            get
            {
                if ((this.mUISửaButton == null))
                {
                    this.mUISửaButton = new WinButton(this);
                    #region Search Criteria
                    this.mUISửaButton.SearchProperties[WinButton.PropertyNames.Name] = "Sửa";
                    this.mUISửaButton.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUISửaButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUISửaButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxttenWindow : WinWindow
    {
        
        public UITxttenWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtten";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxttenEdit
        {
            get
            {
                if ((this.mUITxttenEdit == null))
                {
                    this.mUITxttenEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxttenEdit.SearchProperties[WinEdit.PropertyNames.Name] = "Mã Nhà CC";
                    this.mUITxttenEdit.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUITxttenEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxttenEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtdcWindow : WinWindow
    {
        
        public UITxtdcWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtdc";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtdcEdit
        {
            get
            {
                if ((this.mUITxtdcEdit == null))
                {
                    this.mUITxtdcEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtdcEdit.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUITxtdcEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtdcEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtdtWindow : WinWindow
    {
        
        public UITxtdtWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtdt";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public WinEdit UITxtdtEdit
        {
            get
            {
                if ((this.mUITxtdtEdit == null))
                {
                    this.mUITxtdtEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtdtEdit.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUITxtdtEdit;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUITxtdtEdit;
        #endregion
    }


    //trang thai
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UITxtTrangThaiWindow : WinWindow
    {

        public UITxtTrangThaiWindow(UITestControl searchLimitContainer) :
            base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "txtTrangThai";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }

        #region Properties
        public WinEdit UITxtTrangThaiEdit
        {
            get
            {
                if ((this.mUITxtTrangThaiEdit == null))
                {
                    this.mUITxtTrangThaiEdit = new WinEdit(this);
                    #region Search Criteria
                    this.mUITxtTrangThaiEdit.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUITxtTrangThaiEdit;
            }
        }
        #endregion

        #region Fields
        private WinEdit mUITxtTrangThaiEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.50727.1")]
    public class UILưuWindow : WinWindow
    {
        
        public UILưuWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btluu";
            this.WindowTitles.Add("Nhà Cung Cấp");
            #endregion
        }
        
        #region Properties
        public WinButton UILưuButton
        {
            get
            {
                if ((this.mUILưuButton == null))
                {
                    this.mUILưuButton = new WinButton(this);
                    #region Search Criteria
                    this.mUILưuButton.SearchProperties[WinButton.PropertyNames.Name] = "Lưu";
                    this.mUILưuButton.WindowTitles.Add("Nhà Cung Cấp");
                    #endregion
                }
                return this.mUILưuButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUILưuButton;
        #endregion
    }
}
